### ISSUE TITLE
Open basic API design question for ConnectedStore

### ISSUE THREAD

**Issue by davidhq** [uniqpath/connectome#3]
### Background

Instances `ConnectedStore` live in the frontend (browser) and they conform to the [Svelte store contract](https://svelte.dev/docs#Store_contract).

`ConnectedStore` gets the data from `MirroringStore` in the backend (for example nodejs process).

State of `ConnectedStore` exactly mirrors the state set in the `MirroringStore`:

**Backend:**

```js
const store = new MirroringStore();
store.set({ name: 'John', age: 27 });
```

**Frontend** (example for Svelte but it can be used inside any framework):

```js
const store = new ConnectedStore({ ip, port, protocol, lane });

$: name = $store.name;
```

Svelte template with automatic reactive bindings:

```html
<span>{name} ({$store.age})</span> <!-- two different approaches for the same result -->
```

This is all we need to keep both endpoints fully synced and so if **on the backend** we do:

```js
store.set({ ...store.get(), age: 28 });
```

Our **frontends** will automatically change in an instant and all open (borwser or other type) GUIs will have the latest `age` value displayed.

## Connected store 'connection state'

We also need to include a special meta-state `connected` which tells us if we currently have a live and working connection between two stores (`MirroringStore` on backend and `ConnectedStore` on frontend).

### Option 1

```js
$: connected = $store.connected;
$: name = $store.name;
...
```

Svelte template:

```html
<span class="status" class:ready={connected}>Connected {connected ? '✓' : '✖'}</span>

...
```

This is how it is currently implemented.

### Option 2

```js
const { connected } = store;
$: name = $store.name;
...
```

Svelte template:

```html
<span class="status" class:ready={$connected}>Connected {$connected ? '✓' : '✖'}</span>

...
```

This is an alternative implementation where `connected` property is not merged into the state coming from backend.

Instead `connected` is another simple `writableStore` attached to `ConnectedStore` as its property.

Pros:
- logically it makes more sense
- in case there needs to be more meta-information like this all of tthose can be separate stores instead of potentially clashing with properties coming from backend

Cons:

- a bit harder to remember the api and `$` has to be used in front of `$connected`

It is a bit harder to remember but probably clearner in any case.

Unfortunately this does not work in Svelte as a shortcut:

```js
$: connected = store.$connected; // ⚠️ this does not work
$: name = $store.name;
...
```

Code to make `connected` variable reactive would be:

```js
const { connected: connectedStore } = store;
$: connected = $connectedStore;
$: name = $store.name;
...
```

this is just as an illustration, it is not a clean way and is also too long.

So with Option 2 it will always be the case that with minimal api use we will always utilize `$connected` in templates.

Does Option 2 have any other negative consequences or are there only benefits with consideration that a little bit more to remember (the need for destructuring) and then using `$` in templates is actually better than `cheating` and inserting this part of meta-state inside the state that came over the wire?

**Comment by Vehmloewff** [comment]
I am the author of the suggestion for option 2.

I suggested option 2 to David because there is a problem with option 1: the user's state is modified.  Think about what would happen if the user set his state to have a `connected` property on it.  And it's not just potentially overriding the user's state that is the problem.  Just think if the user was writing the state to `localStorage`.  He would always have to remember to `delete state.connected` before writing.  If he didn't, the `connected` property would become inaccurate, as it no longer being modified by `MirroringStore` when the actual connection drops or reconnects.

@davidhq, I agree with you in your statement that option 2 is a bit messy.  Svelte does not really provide a clean way to accommodate this sort of thing.

Thankfully, we are not just limited to two ways to tackle this problem.  Here are some other options.

We could nest the user's state in a `state` property.

```html
<script>
	const store = MirroringStore({ username: 'Vehmloewff' })
</script>

Connected: {$store.connected}
Username: {$store.state.username}
```

Another option would be to have `MirroringStore` return an object with `store`, and `connected` properties.

```html
<script>
	const { store, connected } = MirroringStore({ username: 'Vehmloewff' })
</script>

Connected: {$connected}
Username: {$store.player}
```

**Comment by davidhq** [comment]
@Vehmloewff very valid points, this saving to `localStorage` issue was also a great illustration of potential problems.

Earlier today I 'flipped' to maybe still consider using Option 1 because I had a use case again and typing just `$: connected = $store.connected` seemed so eary... but then after reading this further elaboration it is now clear that Option 1 is quite a bad idea.

I also like the suggestion that `ConnectedStore` could be a 'generator function'  instead of a contructor... will think more about this and also wait for any further input from other people.

Here is something that [Abdoulie](https://github.com/Anyass3) was [testing](https://svelte.dev/repl/ee175221629048e2aa7bf0b104438a5a?version=3.31.0). I think it won't be useful but it's interesting.. Also I didn't know you can import `get` function from `svelte/store` -- what is this usually used for?

Maybe let's have a broader discussion about state syncing to frontend on this thread during next 1-2 weeks.

There are also some new requirements and ideas: [one example](https://github.com/dmtsys/timeline).

Another use case to consider is how to load state dynamically as various frontend components are loaded and need that state? Now they would each have to create their own ConnectedStore which doesn't seem the best...

There are some great advancement opportunities for this library here ... without breaking any current functionality. Somehow we have to wrap these two new concepts (`loading state dynamically on one connected store` and `loading entire state parts inside component hiearchy`).. I know it's a big topic but are there any suggestions on how to make this as simple as possible... especially in regard to new Svelte releases -- kit and @next ? We still focus on Svelte because this community really thinks things through... if not in the first version then in 3rd or 4th ! Let's try to come up with something really natural to use with new svelte@next routing etc.

Any further suggestions welcome.

Two more things to explore and decide at which point (if at all) they fit into integration efforts (so that we don't duplicate solutions already have already made or soon will):
- [Supabase](https://github.com/supabase/supabase) (esp [client](https://github.com/supabase/supabase-js))
- https://github.com/hasura/graphql-engine (tentative, not so sure anything GraphQL would be a nice fit ?)
- [Yjs](https://github.com/yjs/yjs) for a bit later when we go even further (eventual GUI consistency / CRDTs explorations)

Currently implemented `MirroringStore` + `ConnectedStore` is a simplistic but very well working and useful example ... and something to build further upon because it is only good for minimal simple application prototypes (or 'small apps').

**Comment by davidhq** [comment]
First part of this fix is now implemented: https://github.com/uniqpath/connectome/commit/d507b127eb899c8eaac401af12b8c5a2b2422d52

Usage example: 
https://github.com/dmtsys/svelte-connectome/commit/2ef067d9c17dc717e0e7f8970b7c0cb0298241b7

```js
const { store, connected } = ConnectedStore({ username: 'Vehmloewff' })
```

Regarding this we will see, maybe it does not add enough value, because after all with all the benefits it is not hard to remember:

```js
const { connected } = store;
```

We can still implement generator function that returns two things before Connectome v1.0. I think if we don't find anything else useful that such generator function would return, then we perhaps stay on regular `new` constructor call... and `connected` is simply destructured from store... 

`ConnectedStore` is usually created inside `main.js` and passed to `App.svelte` as a property... and so with generator function two props would always have to be passed.

So (@Vehmloewff) what do you say, is it preferrable to pass in `connected` store into svelte component as a prop or should components in general just destructure any `connected` substores from any connected store they have access to?

**Comment by Vehmloewff** [comment]
I think that the first one would be better because it would be easier to add more properties like `connected` onto it.

I do think, however, that `ConnectedStore` should be renamed to `makeConnectedStore` or `connectedStore`, as it would no longer be a class.

I also think it would be a good idea to rename `store` to `state`.  I think it makes more sense that way.  I am not 100% convinced of this, though, so let me know what you think.

```ts
const { state, connected } = makeConnectedStore({ username: 'Vehmloewff' })
```

**Comment by davidhq** [comment]
Ok. `makeConnectedStore` sounds good.

I'll implement that part now and think about `connected state` in the meantime... I liked the idea because `store` is something that wraps the `state` and state's `connected` attributed. It's almost a design question outside of code.

It also makes sense because then you know that all you can do with such state is reference its (reactive) properties:

```js
$: deviceName = $state.deviceName
```

But looking at this it feels a bit weird because `$` is usually in front of `store` ... 

So what other benefits would calling it `state` bring? There seems to be an initial confusion when writting code like this.

Except of course:

```js
const { state: backend, connected } = makeConnectedStore({ username: 'Vehmloewff' })
```

then:

```js
$: deviceName = $backend.deviceName
```

Now it seems better than passing explicit `state` objects around.

**Comment by davidhq** [comment]
Expanded implementation:

```js
import ConnectedStore from './connectedStore/connectedStore.js';

export default function makeConnectedStore(opts) {
  const store = new ConnectedStore(opts);

  const { connected, action: sendJSON, remoteObject, connector } = store;

  function sendString(str) {
    connector.send(str);
  }

  return { state: store, connected, sendJSON, sendString, remoteObject };
}
```

**Comment by Vehmloewff** [comment]
@davidhq, 

There are no benefits that I can see from calling it `state`.  It seems to me like it would make more sense to call it `state`, but that is just my opinion.

If `backend` makes more sense to you, then, by all means, implement it that way.

**Comment by davidhq** [comment]
@Vehmloewff no, it does not make more sense to call the object returned from `makeConnectedStore` a "`backend`"... `state` seems fine and it is already implemented as that. I was pointing out that user can destructure and rename `state` to something like `backend` for example to be more clear depending on app or component context. `state` is a bit vague but it's ok or even perfect if that is the name of the object returned from basic factory function.

So the main decision was between `store` vs `state`, not `state` or `store` vs. `backend` :)
